<?php

use yii\db\Schema;
use yii\db\Migration;

class m000009_000002_blog_widget_type_DATA_INSERT extends Migration
{

    public function init()
    {
        $this->db = 'db';
        parent::init();
    }

    public function safeUp()
    {
        $this->batchInsert('{{%blog_widget_type}}',
            ["id", "title", "config"],
            [
                [
                    'id'     => '1',
                    'title'  => '1x2 widget',
                    'config' => '{"type":"3","show_title":"1","active_title":"1","active_title_url":"","title":"","show_category_title":"1","show_category_filter":"0","infinite_scroll":"0","show_pager":"0","load_more_button":"0","show_item_read_more_button":"0","items_count":"2","offset":"","item_image_type":"nthumb","item_read_more_button_text":"Կարդալ ավելին","item_read_more_button_icon_class":"fa fa-eye","show_item_category":"0","show_item_category_icon":"0","show_item_category_with_icon":"0","show_item_views":"0","show_item_date":"1","item_date_type":"dateTime","show_item_title":"1","item_title_length":"50","item_title_suffix":"...","show_item_brief":"1","item_brief_length":"100","item_brief_suffix":"[...]","options":{"tag":"div","id":"","class":"widget_1_x_2","style":""},"header_options":{"tag":"div","id":"","class":"","style":""},"body_options":{"tag":"div","id":"","class":"","style":""},"title_options":{"tag":"div","id":"","class":"widget_title row","style":""},"active_title_options":{"id":"","class":"","style":""},"list_options":{"tag":"div","id":"","class":"","style":""},"item_options":{"tag":"article","id":"","class":"item row","Style":""},"item_body_options":{"tag":"div","id":"","class":"","Style":""},"item_image_container_options":{"tag":"div","id":"","class":"col-xs-3 col-md-12 top-buffer-20-xs","style":""},"item_content_container_options":{"tag":"div","id":"","class":"col-xs-9 col-md-12","style":""},"item_info_container_options":{"tag":"","id":"","class":"text-warning text-right","style":""},"item_title_options":{"tag":"h4","id":"","class":"","style":""},"item_brief_options":{"tag":"p","id":"","class":"","style":""},"item_read_more_button_options":{"id":"","class":"btn btn-default btn-sm","style":"float:right;margin-bottom:10px"},"custom_css":"","custom_js":""}',
                ],
                [
                    'id'     => '2',
                    'title'  => 'Videos Widget',
                    'config' => '{"type":"3","show_title":"1","active_title":"1","active_title_url":"","title":"","show_category_title":"1","show_category_filter":"0","infinite_scroll":"0","show_pager":"0","load_more_button":"0","show_item_read_more_button":"0","items_count":"7","offset":"","item_image_type":"xthumb","item_read_more_button_text":"Կարդալ ավելին","item_read_more_button_icon_class":"fa fa-eye","show_item_category":"0","show_item_category_icon":"0","show_item_category_with_icon":"0","show_item_views":"0","show_item_date":"1","item_date_type":"dateTime","show_item_title":"1","item_title_length":"50","item_title_suffix":"...","show_item_brief":"1","item_brief_length":"100","item_brief_suffix":"[...]","options":{"tag":"div","id":"","class":"widget_videos row hidden","style":""},"header_options":{"tag":"div","id":"","class":"","style":""},"body_options":{"tag":"div","id":"","class":"","style":""},"title_options":{"tag":"div","id":"","class":"widget_title","style":""},"active_title_options":{"id":"","class":"","style":""},"list_options":{"tag":"div","id":"","class":"","style":""},"item_options":{"tag":"article","id":"","class":"col-sm-12","Style":""},"item_body_options":{"tag":"div","id":"","class":"row","Style":""},"item_image_container_options":{"tag":"div","id":"","class":"col-xs-3 top-buffer-20-xs __image","style":""},"item_content_container_options":{"tag":"div","id":"","class":"col-xs-9 __content","style":""},"item_info_container_options":{"tag":"div","id":"","class":"text-warning","style":""},"item_title_options":{"tag":"h3","id":"","class":"__title text-muted","style":""},"item_brief_options":{"tag":"p","id":"","class":"__brief text-muted","style":""},"item_read_more_button_options":{"id":"","class":"btn btn-default __button","style":"float:right;margin-bottom:10px"},"custom_css":".widget_videos {\\r\\nbackground:#222;\\r\\n}","custom_js":"jQuery(document).ready(function(){\\r\\njQuery(\'.widget_videos article\').addClass(\'col-md-6\');\\r\\njQuery(\'.widget_videos article\').eq(0).find(\'.__image\').addClass(\'col-md-12\');\\r\\njQuery(\'.widget_videos article\').eq(0).find(\'.__content\').addClass(\'col-md-12\');\\r\\njQuery(\'.widget_videos article\').slice(1,7).find(\'.__brief\').addClass(\'hidden\');\\r\\n//jQuery(\'.widget_videos article\').slice(1,7).find(\'.__button\').addClass(\'hidden\');\\r\\njQuery(\'.widget_videos article\').slice(1,7).find(\'.__title\').css(\'font-size\',\'100%\');\\r\\njQuery(\'.widget_videos\').removeClass(\'hidden\');\\r\\n});\\r\\n"}',
                ],
                [
                    'id'     => '3',
                    'title'  => 'Popular Widget',
                    'config' => '{"type":"2","show_title":"1","active_title":"0","active_title_url":"","title":"Շատ կարդացվող","show_category_title":"1","show_category_filter":"0","infinite_scroll":"0","show_pager":"0","load_more_button":"0","show_item_read_more_button":"0","items_count":"7","offset":"","item_image_type":"xthumb","item_read_more_button_text":"Կարդալ","item_read_more_button_icon_class":"fa fa-eye","show_item_category":"0","show_item_category_icon":"0","show_item_category_with_icon":"0","show_item_views":"0","show_item_date":"1","item_date_type":"dateTime","show_item_title":"1","item_title_length":"50","item_title_suffix":"...","show_item_brief":"1","item_brief_length":"200","item_brief_suffix":"[...]","options":{"tag":"div","id":"widget_popular","class":"widget_popular row hidden","style":""},"header_options":{"tag":"div","id":"","class":"","style":""},"body_options":{"tag":"div","id":"","class":"","style":""},"title_options":{"tag":"div","id":"","class":"widget_title","style":""},"active_title_options":{"id":"","class":"","style":""},"list_options":{"tag":"div","id":"","class":"","style":""},"item_options":{"tag":"article","id":"","class":"col-sm-12","Style":""},"item_body_options":{"tag":"div","id":"","class":"row","Style":""},"item_image_container_options":{"tag":"div","id":"","class":"col-xs-3 top-buffer-20-xs __image","style":""},"item_content_container_options":{"tag":"div","id":"","class":"col-xs-9 __content","style":""},"item_info_container_options":{"tag":"div","id":"","class":"text-warning","style":""},"item_title_options":{"tag":"h3","id":"","class":"__title text-muted","style":""},"item_brief_options":{"tag":"p","id":"","class":"__brief","style":""},"item_read_more_button_options":{"id":"","class":"btn btn-default __button","style":"float:right;margin-bottom:10px"},"custom_css":".widget_popular {\\r\\nbackground:#fff;\\r\\n}","custom_js":"jQuery(document).ready(function(){\\r\\njQuery(\'.widget_popular article\').addClass(\'col-md-6\');\\r\\njQuery(\'.widget_popular article\').eq(0).find(\'.__image\').addClass(\'col-md-12\');\\r\\njQuery(\'.widget_popular article\').eq(0).find(\'.__content\').addClass(\'col-md-12\');\\r\\njQuery(\'.widget_popular article\').slice(1,7).find(\'.__brief\').addClass(\'hidden\');\\r\\n//jQuery(\'.widget_popular article\').slice(1,7).find(\'.__button\').addClass(\'hidden\');\\r\\njQuery(\'.widget_popular article\').slice(1,7).find(\'.__title\').css(\'font-size\',\'100%\');\\r\\njQuery(\'.widget_popular \').removeClass(\'hidden\');\\r\\n});\\r\\n"}',
                ],
                [
                    'id'     => '4',
                    'title'  => 'Blog style widget',
                    'config' => '{"type":"3","show_title":"1","title":"","show_category_title":"1","infinite_scroll":"1","show_pager":"0","load_more_button":"0","show_item_read_more_button":"1","items_count":"-8","offset":"","item_image_type":"","item_read_more_button_text":"","item_read_more_button_icon_class":"","show_item_category":"0","show_item_category_icon":"0","show_item_category_with_icon":"0","show_item_views":"0","show_item_date":"1","show_item_title":"0","item_title_length":"","item_title_suffix":"","show_item_brief":"0","item_brief_length":"","item_brief_suffix":"","options":{"tag":"","id":"","class":"","style":""},"title_options":{"tag":"","id":"","class":"","style":""},"list_options":{"tag":"","id":"","class":"","style":""},"item_options":{"tag":"","id":"","class":"","Style":""},"item_image_container_options":{"tag":"","id":"","class":"","style":""},"item_content_container_options":{"tag":"","id":"","class":"","style":""},"item_info_container_options":{"tag":"","id":"","class":"","style":""},"item_title_options":{"tag":"","id":"","class":"","style":""},"item_brief_options":{"tag":"","id":"","class":"","style":""},"item_read_more_button_options":{"id":"","class":"","style":""},"custom_css":"","custom_js":""}',
                ],
                [
                    'id'     => '5',
                    'title'  => '1 large 6 small widget',
                    'config' => '{"type":"3","show_title":"1","active_title":"1","active_title_url":"","title":"","show_category_title":"1","show_category_filter":"0","infinite_scroll":"0","show_pager":"0","load_more_button":"0","show_item_read_more_button":"0","items_count":"7","offset":"","item_image_type":"xthumb","item_read_more_button_text":"Կարդալ","item_read_more_button_icon_class":"fa fa-eye","show_item_category":"0","show_item_category_icon":"0","show_item_category_with_icon":"0","show_item_views":"0","show_item_date":"1","item_date_type":"dateTime","show_item_title":"1","item_title_length":"50","item_title_suffix":"...","show_item_brief":"1","item_brief_length":"100","item_brief_suffix":"[...]","options":{"tag":"div","id":"widget_1_lg_6_sm","class":"widget_1_lg_6_sm row hidden","style":""},"header_options":{"tag":"div","id":"","class":"","style":""},"body_options":{"tag":"div","id":"","class":"","style":""},"title_options":{"tag":"div","id":"","class":"widget_title","style":""},"active_title_options":{"id":"","class":"","style":""},"list_options":{"tag":"div","id":"","class":"","style":""},"item_options":{"tag":"article","id":"","class":"col-sm-12","Style":""},"item_body_options":{"tag":"div","id":"","class":"row","Style":""},"item_image_container_options":{"tag":"div","id":"","class":"col-xs-3 top-buffer-20-xs __image","style":""},"item_content_container_options":{"tag":"div","id":"","class":"col-xs-9 __content","style":""},"item_info_container_options":{"tag":"div","id":"","class":"text-warning","style":""},"item_title_options":{"tag":"h3","id":"","class":"__title text-muted","style":""},"item_brief_options":{"tag":"p","id":"","class":"__brief","style":""},"item_read_more_button_options":{"id":"","class":"btn btn-default __button","style":"float:right;margin-bottom:10px"},"custom_css":".widget_1_lg_6_sm{\\r\\nbackground:#fff;\\r\\n}","custom_js":"jQuery(document).ready(function(){\\r\\njQuery(\'.widget_1_lg_6_sm article\').addClass(\'col-md-6\');\\r\\njQuery(\'.widget_1_lg_6_sm article\').eq(0).find(\'.__image\').addClass(\'col-md-12\');\\r\\njQuery(\'.widget_1_lg_6_sm article\').eq(0).find(\'.__content\').addClass(\'col-md-12\');\\r\\njQuery(\'.widget_1_lg_6_sm article\').slice(1,7).find(\'.__brief\').addClass(\'hidden\');\\r\\n//jQuery(\'.widget_1_lg_6_sm article\').slice(1,7).find(\'.__button\').addClass(\'hidden\');\\r\\njQuery(\'.widget_1_lg_6_sm article\').slice(1,7).find(\'.__title\').css(\'font-size\',\'100%\');\\r\\njQuery(\'.widget_1_lg_6_sm \').removeClass(\'hidden\');\\r\\n});\\r\\n"}',
                ],
                [
                    'id'     => '6',
                    'title'  => '3x1 widget',
                    'config' => '{"type":"3","show_title":"1","active_title":"1","active_title_url":"","title":"","show_category_title":"1","show_category_filter":"0","infinite_scroll":"0","show_pager":"0","load_more_button":"0","show_item_read_more_button":"0","items_count":"3","offset":"","item_image_type":"xthumb","item_read_more_button_text":"Կարդալ ավելին","item_read_more_button_icon_class":"fa fa-eye","show_item_category":"0","show_item_category_icon":"0","show_item_category_with_icon":"0","show_item_views":"0","show_item_date":"1","item_date_type":"dateTime","show_item_title":"1","item_title_length":"50","item_title_suffix":"...","show_item_brief":"1","item_brief_length":"100","item_brief_suffix":"[...]","options":{"tag":"div","id":"","class":"widget_3_x_1","style":""},"header_options":{"tag":"div","id":"","class":"","style":""},"body_options":{"tag":"div","id":"","class":"","style":""},"title_options":{"tag":"div","id":"","class":"widget_title row","style":""},"active_title_options":{"id":"","class":"","style":""},"list_options":{"tag":"div","id":"","class":"row","style":""},"item_options":{"tag":"article","id":"","class":"item col-md-4","Style":""},"item_body_options":{"tag":"div","id":"","class":"row","Style":""},"item_image_container_options":{"tag":"div","id":"","class":"col-xs-3 col-md-12 top-buffer-20-xs","style":""},"item_content_container_options":{"tag":"div","id":"","class":"col-xs-9 col-md-12","style":""},"item_info_container_options":{"tag":"","id":"","class":"text-warning text-right","style":""},"item_title_options":{"tag":"h4","id":"","class":"","style":""},"item_brief_options":{"tag":"p","id":"","class":"","style":""},"item_read_more_button_options":{"id":"","class":"btn btn-default btn-sm","style":"float:right;margin-bottom:10px"},"custom_css":"","custom_js":""}',
                ],
                [
                    'id'     => '7',
                    'title'  => '1x1 widget',
                    'config' => '{"type":"3","show_title":"1","active_title":"1","active_title_url":"","title":"","show_category_title":"1","show_category_filter":"0","infinite_scroll":"0","show_pager":"0","load_more_button":"0","show_item_read_more_button":"0","items_count":"1","offset":"","item_image_type":"xthumb","item_read_more_button_text":"Կարդալ ավելին","item_read_more_button_icon_class":"fa fa-eye","show_item_category":"0","show_item_category_icon":"0","show_item_category_with_icon":"0","show_item_views":"0","show_item_date":"1","item_date_type":"dateTime","show_item_title":"1","item_title_length":"50","item_title_suffix":"...","show_item_brief":"1","item_brief_length":"100","item_brief_suffix":"[...]","options":{"tag":"div","id":"","class":"widget_3_x_1 row","style":""},"header_options":{"tag":"div","id":"","class":"","style":""},"body_options":{"tag":"div","id":"","class":"","style":""},"title_options":{"tag":"div","id":"","class":"widget_title","style":""},"active_title_options":{"id":"","class":"","style":""},"list_options":{"tag":"div","id":"","class":"","style":""},"item_options":{"tag":"article","id":"","class":"item","Style":""},"item_body_options":{"tag":"div","id":"","class":"","Style":""},"item_image_container_options":{"tag":"div","id":"","class":"col-xs-3 col-md-12 top-buffer-20-md top-buffer-10-xs bottom-buffer-10-xs","style":""},"item_content_container_options":{"tag":"div","id":"","class":"col-xs-9 col-md-12","style":""},"item_info_container_options":{"tag":"","id":"","class":"text-warning text-right","style":""},"item_title_options":{"tag":"h4","id":"","class":"","style":""},"item_brief_options":{"tag":"p","id":"","class":"","style":""},"item_read_more_button_options":{"id":"","class":"btn btn-default btn-sm","style":"float:right;margin-bottom:10px"},"custom_css":"","custom_js":""}',
                ],
                [
                    'id'     => '8',
                    'title'  => 'Dynamic news feed widget',
                    'config' => '{"title":"Feed","items_count":15,"show_item_brief":false,"active_title":true,"active_title_url":"\/","show_title":true,"show_category_filter":true,"show_category_title":true,"header_options":{"tag":"div","class":"header"},"item_brief_length":50,"infinite_scroll":true,"item_date_type":"dateTime","id":"home_feed_widget","item_image_type":"xsthumb","item_title_length":70,"title_options":{"class":"widget_title"},"item_title_options":{"class":"top-buffer-10-xs"},"item_info_container_options":{"class":"text-right text-warning small"},"item_image_container_options":{"class":"col-xs-2 left-padding-0-xs right-padding-10-xs"},"item_content_container_options":{"class":"col-xs-10 nospaces-xs"},"item_options":{"tag":"article","class":"item col-xs-12 top-buffer-10-xs left-padding-0-xs right-padding-10-xs"},"list_options":{"class":"feed-widget-listview","style":"overflow-y: scroll; max-height: 100vh;"},"custom_js":"var sidebar = new StickySidebar(\'#home-feed-container\', {\r\n    containerSelector: \'#main-content>.container\',\r\n    innerWrapperSelector: \'#home_feed\',\r\n    topSpacing: 0,\r\n    bottomSpacing: 0,\r\n    resizeSensor: true,\r\n    minWidth: 991\r\n});\r\nfunction fixFeedHeight(){\r\n      var headerHeight = $(\'#home_feed_widget > .header\').outerHeight();\r\n      var winHeight = $(window).outerHeight();\r\n      var widgetHeight = winHeight - headerHeight;\r\n      var widget = $(\'#home_feed_widget .feed-widget-listview\');\r\n      widget.height(widgetHeight);\r\n}\r\n$(window).on(\'load ready resize\', function(){fixFeedHeight();sidebar.updateSticky();});\r\n$(document).ready(function(){fixFeedHeight();sidebar.updateSticky();});"}',
                ],
                [
                    'id'     => '9',
                    'title'  => 'Static news feed widget',
                    'config' => '{"items_count":10,"title":"News Feed","title_options":{"tag":"div","class":"widget_title"},"show_title":true,"show_item_brief":false,"item_options":{"class":"col-xs-12 top-buffer-20-xs"},"item_body_options":{"class":"row"},"item_image_type":"xsthumb","show_item_category_icon":false,"item_brief_length":50,"item_date_type":"dateTime","item_info_container_options":{"class":"text-warning text-right small"},"id":"post_feed_widget"}',
                ],
                [
                    'id'     => '10',
                    'title'  => 'Popular posts widget (sidebar)',
                    'config' => '{"items_count":10,"title":"News Feed","title_options":{"tag":"div","class":"widget_title"},"show_title":true,"show_item_brief":false,"item_options":{"class":"col-xs-12 top-buffer-20-xs"},"item_body_options":{"class":"row"},"item_image_type":"xsthumb","show_item_category_icon":false,"item_brief_length":50,"item_date_type":"dateTime","item_info_container_options":{"class":"text-warning text-right small"},"id":"post_feed_widget"}',
                ],
            ]
        );
    }

    public function safeDown()
    {
        //$this->truncateTable('{{%blog_widget_type}} CASCADE');
    }
}
