<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    'Welcome to Blog Module' => 'Բարի գալուստ',
    'A comment has been added and is awaiting validation' => 'Մեկնաբանությունը ավելացվել է և գտնվում է հաստատման փուլում։',
    'Action not found' => 'Գործողություն չի հայտնաբերվել',
    'Actions' => 'Գործողություն',
    'Add Sub Category' => 'Ավելացնել ենթաբաժին',
    'Add comments' => 'Ավելացնել մեկնաբանություն',
    'Are you sure you want to delete this item?' => 'Վստա՞հ եք, որ ցանկանում եք ջնջել այս։',
    'Author' => 'Հեղինակ',
    'Banner' => 'Գլխավոր նկար',
    'Blog' => 'Գրառումներ',
    'Blog Category' => 'Բաժին',
    'Blog Categories' => 'Բաժիններ',
    'Blog Comment' => 'Մեկնաբանություն',
    'Blog Comments' => 'Մեկնաբանություններ',
    'Blog Post' => 'Գրառում',
    'Blog Posts' => 'Գրառումներ',
    'Blog Tag' => 'Թեգ',
    'Blog Tags' => 'Թեգեր',
    'Brief' => 'Կարճ նկարագրություն',
    'CONSTANT_NO' => 'ՈՉ',
    'CONSTANT_YES' => 'ԱՅՈ',
    'Category' => 'Բաժին',
    'Category ID' => 'Բաժնի Հ/Հ',
    'Click' => 'Դիտումներ',
    'Comments' => 'Մեկնաբանություններ',
    'Comments Count' => 'Մեկնաբանութ․ քանակը',
    'Confirm' => 'Հաստատել',
    'Content' => 'Տեքստ',
    'Create' => 'Ստեղծել',
    'Create ' => 'Ստեղծել ',
    'Create Time' => 'Ստեղծման ժամանակը',
    'Created At' => 'Ստեղծված',
    'Delete' => 'Ջնջել',
    'Email' => 'Էլ․ Փոստ',
    'Frequency' => 'Հաճախականություն',
    'ID' => 'Հ/Հ',
    'Is Nav' => 'Նավիգացիա',
    'Is Slide' => 'Սլայդ',
    'Math, for example, 45-12 = 33' => 'Գրեք լուծումը, օրինակ՝ 45-12 = 33',
    'NO' => 'Ոչ',
    'Name' => 'Անուն',
    'PAGE_TYPE_LIST' => 'Լիստ',
    'PAGE_TYPE_PAGE' => 'Հասարակ Էջ',
    'PROMPT_STATUS' => 'Կարգավիճակը',
    'Page Size' => 'Էջի չափերը',
    'Parent ID' => 'Ծնողական Հ/Հ',
    'Please Filter' => 'Ֆիլտր',
    'Post ID' => 'Գրառման Հ/Հ',
    'Redirect Url' => 'Վերահղման URL',
    'Reset' => 'Վերագործարկել',
    'Root Category' => 'Արմատային բաժին',
    'Search' => 'Փնտրել',
    'Send' => 'Ուղարկել',
    'Slug' => 'Սղանուն',
    'Sort Order' => 'Դասավորություն',
    'Status' => 'Կարգավիճակ',
    'Successfully confirm' => 'Հաջողությամբ Հաստատվեց',
    'Successfully delete' => 'Հաջողությամբ ջնջվեց',
    'Tags' => 'Թեգեր',
    'Template' => 'Շաբլոն',
    'Title' => 'Վերնագիր',
    'Update' => 'Փոփոխել',
    'Update ' => 'Փոփոխել ',
    'Updated At' => 'Թարմացված',
    'Url' => 'Url',
    'User ID' => 'Օգտատիրոջ Հ/Հ',
    'Verify code' => 'Ստուգման կոդ',
    'View' => 'Դիտել',
    'Read more'=>'Կարդալ ավելին',
    'Play video'=>'Դիտել տեսանյութը',
    'Write comments' => 'Գրել մեկնաբանություն',
    'YES' => 'Այո',
    'STATUS_INACTIVE'=>'Ապաակտիվացված',
    'STATUS_ACTIVE'=>'Ակտիվ',
    'STATUS_DELETED'=>'Ջնջված',
    'Show In Slider'=>'Ցուցադրել սլայդերում',
    'General'=>'Գլխավոր',
    'Insert banner code'=>'Ավելացրեք բանների կոդը',
    'Popular posts'=>'Շատ ընթերցվողներ',
    'Videos'=>'Տեսանյութեր'

];
